CREATE TABLE `product`(
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '商品名',
    `price` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '价格',
    `store` INT(11) NOT NULL DEFAULT 0 COMMENT '库存',
    `detail` VARCHAR(255)  DEFAULT '' COMMENT '描述',
    PRIMARY KEY (`id`)
) ENGINE= INNODB DEFAULT  CHARSET = utf8 COMMENT ='商品表' AUTO_INCREMENT = 1