/*
 Navicat Premium Data Transfer

 Source Server         : 本地
 Source Server Type    : MySQL
 Source Server Version : 50726
 Source Host           : localhost:3306


 Target Server Type    : MySQL
 Target Server Version : 50726
 File Encoding         : 65001

 Date: 14/08/2020 11:15:59
*/

SET NAMES utf8mb4;
-- ----------------------------
-- Table structure for express
-- ----------------------------
DROP TABLE IF EXISTS `express`;
CREATE TABLE `express`  (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '快递名称',
  `simplecode` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '快递简码',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1101 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '快递表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of express
-- ----------------------------
INSERT INTO `express` VALUES (1, '圆通速递', 'yuatog');
INSERT INTO `express` VALUES (2, '韵达快递', 'yuda');
INSERT INTO `express` VALUES (3, '中通快递', 'zhogtog');
INSERT INTO `express` VALUES (4, '顺丰速运', 'shufeg');
INSERT INTO `express` VALUES (5, '邮政快递包裹', 'youzhegguoei');
INSERT INTO `express` VALUES (6, '百世快递', 'huitogkuaidi');
INSERT INTO `express` VALUES (7, '京东物流', 'jd');
INSERT INTO `express` VALUES (8, '申通快递', 'shetog');
INSERT INTO `express` VALUES (9, '天天快递', 'tiatia');
INSERT INTO `express` VALUES (10, 'EMS', 'ems');
INSERT INTO `express` VALUES (11, '极兔速递', 'jtexpress');
INSERT INTO `express` VALUES (12, '邮政标准快递', 'youzhegbk');
INSERT INTO `express` VALUES (13, '德邦', 'debagwuliu');
INSERT INTO `express` VALUES (14, '宅急送', 'zhaijisog');
INSERT INTO `express` VALUES (15, '德邦快递', 'debagkuaidi');
INSERT INTO `express` VALUES (16, '苏宁物流', 'suig');
INSERT INTO `express` VALUES (17, '众邮快递', 'zhogyouex');
INSERT INTO `express` VALUES (18, '优速快递', 'youshuwuliu');
INSERT INTO `express` VALUES (19, '百世快运', 'baishiwuliu');
INSERT INTO `express` VALUES (20, '韵达快运', 'yudakuaiyu');
INSERT INTO `express` VALUES (21, '中通快运', 'zhogtogkuaiyu');
INSERT INTO `express` VALUES (22, '安能快运', 'aegwuliu');
INSERT INTO `express` VALUES (23, '宇捷通', 'yujtog');
INSERT INTO `express` VALUES (24, '圆通快运', 'yuatogkuaiyu');
INSERT INTO `express` VALUES (25, '国际包裹', 'youzhegguoji');
INSERT INTO `express` VALUES (26, '丹鸟', 'daiao');
INSERT INTO `express` VALUES (27, 'FedEx-国际件', 'fedex');
INSERT INTO `express` VALUES (28, 'DHL-全球件', 'dhle');
INSERT INTO `express` VALUES (29, 'EWE全球快递', 'ewe');
INSERT INTO `express` VALUES (30, '中通国际', 'zhogtogguoji');
INSERT INTO `express` VALUES (31, '特急送', 'ltjs');
INSERT INTO `express` VALUES (32, '跨越速运', 'kuayue');
INSERT INTO `express` VALUES (33, 'DHL-中国件', 'dhl');
INSERT INTO `express` VALUES (34, 'UPS-全球件', 'upse');
INSERT INTO `express` VALUES (35, '中铁快运', 'ztky');
INSERT INTO `express` VALUES (36, 'USPS', 'usps');
INSERT INTO `express` VALUES (37, '壹米滴答', 'yimidida');
INSERT INTO `express` VALUES (38, '速尔快递', 'suer');
INSERT INTO `express` VALUES (39, '同城快寄', 'shpost');
INSERT INTO `express` VALUES (40, '九曳供应链', 'jiuyescm');
INSERT INTO `express` VALUES (41, 'EMS-国际件', 'emsguoji');
INSERT INTO `express` VALUES (42, '递四方', 'disifag');
INSERT INTO `express` VALUES (43, '日日顺物流', 'rrs');
INSERT INTO `express` VALUES (44, '安得物流', 'ato');
INSERT INTO `express` VALUES (45, 'UPS', 'ups');
INSERT INTO `express` VALUES (46, '速必达', 'subida');
INSERT INTO `express` VALUES (47, 'EMS包裹', 'emsbg');
INSERT INTO `express` VALUES (48, '联邦快递', 'liabagkuaidi');
INSERT INTO `express` VALUES (49, '芝麻开门', 'zhimakaime');
INSERT INTO `express` VALUES (50, '微特派', 'weitepai');
INSERT INTO `express` VALUES (51, '卓志速运', 'chiaicip');
INSERT INTO `express` VALUES (52, '联昊通', 'liahaowuliu');
INSERT INTO `express` VALUES (53, '顺心捷达', 'sxjdfreight');
INSERT INTO `express` VALUES (54, '优邦速运', 'uboex');
INSERT INTO `express` VALUES (55, 'D速快递', 'dsukuaidi');
INSERT INTO `express` VALUES (56, '中邮物流', 'zhogyouwuliu');
INSERT INTO `express` VALUES (57, '宇鑫物流', 'yuxiwuliu');
INSERT INTO `express` VALUES (58, '富吉速运', 'fujisuyu');
INSERT INTO `express` VALUES (59, '龙邦速递', 'logbawuliu');
INSERT INTO `express` VALUES (60, '快捷速递', 'kuaijiesudi');
INSERT INTO `express` VALUES (61, '美快国际物流', 'meiquick');
INSERT INTO `express` VALUES (62, '转运四方', 'zhuayusifag');
INSERT INTO `express` VALUES (63, '联合快递', 'gslhkd');
INSERT INTO `express` VALUES (64, '信丰物流', 'xifegwuliu');
INSERT INTO `express` VALUES (65, '邦泰快运', 'btexpress');
INSERT INTO `express` VALUES (66, '日本（Japa Post）', 'japaposte');
INSERT INTO `express` VALUES (67, '圆通国际', 'yuatogguoji');
INSERT INTO `express` VALUES (68, '新顺丰（NSF）', 'sf');
INSERT INTO `express` VALUES (69, '云邮跨境快递', 'hkems');
INSERT INTO `express` VALUES (70, '鑫正一快递', 'zhegyikuaidi');
INSERT INTO `express` VALUES (71, 'YUN TRACK', 'yutrack');
INSERT INTO `express` VALUES (72, '国通快递', 'guotogkuaidi');
INSERT INTO `express` VALUES (73, '澳洲飞跃物流', 'rlgaus');
INSERT INTO `express` VALUES (74, '澳大利亚(Australia Post)', 'auspost');
INSERT INTO `express` VALUES (75, '京广速递', 'jiguagsudikuaijia');
INSERT INTO `express` VALUES (76, '澳邮中国快运', 'auexpress');
INSERT INTO `express` VALUES (77, '程光快递', 'flyway');
INSERT INTO `express` VALUES (78, 'DPD', 'dpd');
INSERT INTO `express` VALUES (79, 'TNT', 'tt');
INSERT INTO `express` VALUES (80, '燕文物流', 'yw56');
INSERT INTO `express` VALUES (81, '汇森速运', 'huiseky');
INSERT INTO `express` VALUES (82, '海信物流', 'savor');
INSERT INTO `express` VALUES (83, '洋包裹', 'yagbaoguo');
INSERT INTO `express` VALUES (84, 'Austa国际速递', 'austa');
INSERT INTO `express` VALUES (85, '合众速递(UCS）', 'ucs');
INSERT INTO `express` VALUES (86, '中通（带电话）', 'zhogtogphoe');
INSERT INTO `express` VALUES (87, '方舟速递', 'arkexpress');
INSERT INTO `express` VALUES (88, '时达通', 'jssdt56');
INSERT INTO `express` VALUES (89, '加拿大(Caada Post)', 'capost');
INSERT INTO `express` VALUES (90, '叁虎物流', 'sahuwuliu');
INSERT INTO `express` VALUES (91, '斑马物流', 'bama');
INSERT INTO `express` VALUES (92, '申通国际', 'stosolutio');
INSERT INTO `express` VALUES (93, '上海缤纷物流', 'bflg');
INSERT INTO `express` VALUES (94, '美西快递', 'meixi');
INSERT INTO `express` VALUES (95, '天地华宇', 'tiadihuayu');
INSERT INTO `express` VALUES (96, 'Superb Grace', 'superb');
INSERT INTO `express` VALUES (97, '速达通', 'sdto');
INSERT INTO `express` VALUES (98, 'Xlobo贝海国际', 'xlobo');
INSERT INTO `express` VALUES (99, 'TNT-全球件', 'tte');
INSERT INTO `express` VALUES (100, '安能快递', 'ae66');
INSERT INTO `express` VALUES (101, '中环快递', 'zhoghua');
INSERT INTO `express` VALUES (102, '广东邮政', 'guagdogyouzhegwuliu');
INSERT INTO `express` VALUES (103, '加运美', 'jiayumeiwuliu');
INSERT INTO `express` VALUES (104, '联合速运', 'uitedex');
INSERT INTO `express` VALUES (105, 'DHL-德国件（DHL Deutschlad）', 'dhlde');
INSERT INTO `express` VALUES (106, '新杰物流', 'sujex');
INSERT INTO `express` VALUES (107, '安迅物流', 'axl');
INSERT INTO `express` VALUES (108, '转运中国', 'uszc');
INSERT INTO `express` VALUES (109, '全峰快递', 'quafegkuaidi');
INSERT INTO `express` VALUES (110, '盛丰物流', 'sfwl');
INSERT INTO `express` VALUES (111, '比利时（Bpost）', 'bpost');
INSERT INTO `express` VALUES (112, '澳德物流', 'auod');
INSERT INTO `express` VALUES (113, '安达速递', 'adapost');
INSERT INTO `express` VALUES (114, 'UEQ快递', 'ueq');
INSERT INTO `express` VALUES (115, 'OCS', 'ocs');
INSERT INTO `express` VALUES (116, '盛辉物流', 'sheghuiwuliu');
INSERT INTO `express` VALUES (117, '富腾达国际货运', 'ftd');
INSERT INTO `express` VALUES (118, '如风达', 'rufegda');
INSERT INTO `express` VALUES (119, '万象物流', 'waxiagwuliu');
INSERT INTO `express` VALUES (120, '疯狂快递', 'crazyexpress');
INSERT INTO `express` VALUES (121, '广东速腾物流', 'suteg');
INSERT INTO `express` VALUES (122, 'Aramex', 'aramex');
INSERT INTO `express` VALUES (123, '中速快递', 'zhogsukuaidi');
INSERT INTO `express` VALUES (124, '中铁物流', 'zhogtiewuliu');
INSERT INTO `express` VALUES (125, 'EMS-国际件-英文', 'emsite');
INSERT INTO `express` VALUES (126, '恒路物流', 'hegluwuliu');
INSERT INTO `express` VALUES (127, '美通', 'valueway');
INSERT INTO `express` VALUES (128, '美国申通', 'stoexpress');
INSERT INTO `express` VALUES (129, '平安达腾飞', 'pigadategfei');
INSERT INTO `express` VALUES (130, '成都立即送', 'lijisog');
INSERT INTO `express` VALUES (131, '中邮速递', 'wodersyd');
INSERT INTO `express` VALUES (132, '天马迅达', 'tiama');
INSERT INTO `express` VALUES (133, '极地快递', 'polarexpress');
INSERT INTO `express` VALUES (134, '荷兰邮政-中文(PostNL iteratioal registered mail)', 'postlc');
INSERT INTO `express` VALUES (135, '龙邦物流', 'lbex');
INSERT INTO `express` VALUES (136, '海带宝', 'haidaibao');
INSERT INTO `express` VALUES (137, '百福东方', 'baifudogfag');
INSERT INTO `express` VALUES (138, '中国香港(HogKog Post)', 'hkpost');
INSERT INTO `express` VALUES (139, '速通物流', 'sut56');
INSERT INTO `express` VALUES (140, '景顺物流', 'jigshu');
INSERT INTO `express` VALUES (141, '万家物流', 'wajiawuliu');
INSERT INTO `express` VALUES (142, '金岸物流', 'jia');
INSERT INTO `express` VALUES (143, '新西兰（New Zealad Post）', 'ewzealad');
INSERT INTO `express` VALUES (144, '易达通快递', 'qexpress');
INSERT INTO `express` VALUES (145, '一速递', 'oeexpress');
INSERT INTO `express` VALUES (146, '全日通', 'quaritogkuaidi');
INSERT INTO `express` VALUES (147, 'CJ物流', 'doortodoor');
INSERT INTO `express` VALUES (148, '宏递快运', 'hd');
INSERT INTO `express` VALUES (149, '环球速运', 'huaqiu');
INSERT INTO `express` VALUES (150, 'EMS-英文', 'emse');
INSERT INTO `express` VALUES (151, '黄马甲', 'huagmajia');
INSERT INTO `express` VALUES (152, 'AAE-中国件', 'aae');
INSERT INTO `express` VALUES (153, '鼎润物流', 'la911');
INSERT INTO `express` VALUES (154, 'TrasRush', 'trasrush');
INSERT INTO `express` VALUES (155, '出口易', 'chukou1');
INSERT INTO `express` VALUES (156, '达发物流', 'dfwl');
INSERT INTO `express` VALUES (157, '长江国际速递', 'chagjiag');
INSERT INTO `express` VALUES (158, 'Fedex-国际件-中文', 'fedexc');
INSERT INTO `express` VALUES (159, '德坤物流', 'dekuc');
INSERT INTO `express` VALUES (160, '增益速递', 'zegyisudi');
INSERT INTO `express` VALUES (161, 'TNT Australia', 'ttau');
INSERT INTO `express` VALUES (162, 'Capar', 'capar');
INSERT INTO `express` VALUES (163, '中翼国际物流', 'chexp');
INSERT INTO `express` VALUES (164, '澳天速运', 'aotsd');
INSERT INTO `express` VALUES (165, '聚盟共建', 'jumstc');
INSERT INTO `express` VALUES (166, '德国优拜物流', 'ubuy');
INSERT INTO `express` VALUES (167, '嘉里大通', 'jialidatog');
INSERT INTO `express` VALUES (168, '大田物流', 'datiawuliu');
INSERT INTO `express` VALUES (169, '佐川急便', 'sagawa');
INSERT INTO `express` VALUES (170, '泛捷国际速递', 'epaex');
INSERT INTO `express` VALUES (171, '集先锋快递', 'jxfex');
INSERT INTO `express` VALUES (172, '速派快递', 'fastgoexpress');
INSERT INTO `express` VALUES (173, '全联速运', 'guexp');
INSERT INTO `express` VALUES (174, '韵丰物流', 'yufeg56');
INSERT INTO `express` VALUES (175, 'TST速运通', 'tstexp');
INSERT INTO `express` VALUES (176, '宅急便', 'zhaijibia');
INSERT INTO `express` VALUES (177, '法国小包（colissimo）', 'colissimo');
INSERT INTO `express` VALUES (178, '荷兰邮政-中国件', 'postlchia');
INSERT INTO `express` VALUES (179, '汇通天下物流', 'httx56');
INSERT INTO `express` VALUES (180, 'FedEx-美国件', 'fedexus');
INSERT INTO `express` VALUES (181, 'COE', 'coe');
INSERT INTO `express` VALUES (182, '联邦快递-英文', 'liabagkuaidie');
INSERT INTO `express` VALUES (183, '泰国138国际物流', 'sd138');
INSERT INTO `express` VALUES (184, '大马鹿', 'idamalu');
INSERT INTO `express` VALUES (185, 'CNPEX中邮快递', 'cpex');
INSERT INTO `express` VALUES (186, '迅达速递', 'xdexpress');
INSERT INTO `express` VALUES (187, '运通速运', 'yutog');
INSERT INTO `express` VALUES (188, '秦远物流', 'qiyua');
INSERT INTO `express` VALUES (189, '瀚朝物流', 'hac56');
INSERT INTO `express` VALUES (190, '苏通快运', 'zjstky');
INSERT INTO `express` VALUES (191, '顺丰快运', 'shufegkuaiyu');
INSERT INTO `express` VALUES (192, '铁中快运', 'tzky');
INSERT INTO `express` VALUES (193, 'DPEX', 'dpex');
INSERT INTO `express` VALUES (194, '鸿泰物流', 'hht56');
INSERT INTO `express` VALUES (195, '亚洲顺物流', 'yzswuliu');
INSERT INTO `express` VALUES (196, '商桥物流', 'shagqiao56');
INSERT INTO `express` VALUES (197, '优优速递', 'youyou');
INSERT INTO `express` VALUES (198, '考拉速递', 'koalaexp');
INSERT INTO `express` VALUES (199, '佳怡物流', 'jiayiwuliu');
INSERT INTO `express` VALUES (200, '欧亚专线', 'euasia');
INSERT INTO `express` VALUES (201, '百事亨通', 'bsht');
INSERT INTO `express` VALUES (202, '三真驿道', 'zlik');
INSERT INTO `express` VALUES (203, '西班牙(Correos de Espa?a)', 'correosdees');
INSERT INTO `express` VALUES (204, '德国(Deutsche Post)', 'deutschepost');
INSERT INTO `express` VALUES (205, '源安达', 'yuaada');
INSERT INTO `express` VALUES (206, 'UBI Australia', 'gotoubi');
INSERT INTO `express` VALUES (207, '品骏快递', 'pjbest');
INSERT INTO `express` VALUES (208, '威盛快递', 'wherexpess');
INSERT INTO `express` VALUES (209, '耀飞同城快递', 'yaofeikuaidi');
INSERT INTO `express` VALUES (210, 'LUCFLOW EXPRESS', 'logfx');
INSERT INTO `express` VALUES (211, '佳吉快运', 'jiajiwuliu');
INSERT INTO `express` VALUES (212, '极光转运', 'jiguag');
INSERT INTO `express` VALUES (213, '东方汇', 'est365');
INSERT INTO `express` VALUES (214, '原飞航', 'yuafeihagwuliu');
INSERT INTO `express` VALUES (215, 'CNE', 'cexps');
INSERT INTO `express` VALUES (216, '景光物流', 'jgwl');
INSERT INTO `express` VALUES (217, '西翼物流', 'westwig');
INSERT INTO `express` VALUES (218, '全一快递', 'quayikuaidi');
INSERT INTO `express` VALUES (219, 'EFS Post（平安快递）', 'efs');
INSERT INTO `express` VALUES (220, '锦程快递', 'hrex');
INSERT INTO `express` VALUES (221, '淘布斯国际物流', 'taoplus');
INSERT INTO `express` VALUES (222, '飞洋快递', 'shipgce');
INSERT INTO `express` VALUES (223, 'TCXB国际物流', 'tcxbthai');
INSERT INTO `express` VALUES (224, '荷兰邮政(PostNL iteratioal registered mail)', 'postl');
INSERT INTO `express` VALUES (225, '易客满', 'ecmsc');
INSERT INTO `express` VALUES (226, '速递中国', 'sedtochia');
INSERT INTO `express` VALUES (227, '一号仓', 'oehcag');
INSERT INTO `express` VALUES (228, '运通中港快递', 'ytkd');
INSERT INTO `express` VALUES (229, '全时速运', 'ruhegfeg');
INSERT INTO `express` VALUES (230, '顺丰-繁体', 'shufeghk');
INSERT INTO `express` VALUES (231, '意大利(Poste Italiae)', 'italiae');
INSERT INTO `express` VALUES (232, '龙枫国际快递', 'lfexpress');
INSERT INTO `express` VALUES (233, '商壹国际物流', 'com1express');
INSERT INTO `express` VALUES (234, 'CHS中环国际快递', 'chszhoghuaguoji');
INSERT INTO `express` VALUES (235, '安鲜达', 'exfresh');
INSERT INTO `express` VALUES (236, '锋鸟物流', 'beebird');
INSERT INTO `express` VALUES (237, '飞远配送', 'feiyuavipshop');
INSERT INTO `express` VALUES (238, '优速通达', 'yousutogda');
INSERT INTO `express` VALUES (239, '易境达国际物流', 'uscbexpress');
INSERT INTO `express` VALUES (240, '南方传媒物流', 'dwl');
INSERT INTO `express` VALUES (241, '一正达速运', 'yizhegdasuyu');
INSERT INTO `express` VALUES (242, 'Toll', 'dpexe');
INSERT INTO `express` VALUES (243, '佰麒快递', 'beckygo');
INSERT INTO `express` VALUES (244, '城通物流', 'chegtog');
INSERT INTO `express` VALUES (245, '英国大包、EMS（Parcel Force）', 'parcelforce');
INSERT INTO `express` VALUES (246, '新元国际', 'xyyc');
INSERT INTO `express` VALUES (247, '明通国际快递', 'tjex');
INSERT INTO `express` VALUES (248, 'DHL Beelux', 'dhlbeelux');
INSERT INTO `express` VALUES (249, '中澳速递', 'causu');
INSERT INTO `express` VALUES (250, '中远e环球', 'cosco');
INSERT INTO `express` VALUES (251, '韩国（Korea Post）', 'koreapost');
INSERT INTO `express` VALUES (252, '尚橙物流', 'shagcheg');
INSERT INTO `express` VALUES (253, '法国(La Poste)', 'csuivi');
INSERT INTO `express` VALUES (254, '全速通', 'quasutog');
INSERT INTO `express` VALUES (255, '黑猫宅急便', 'tcat');
INSERT INTO `express` VALUES (256, '威时沛运货运', 'wtdchia');
INSERT INTO `express` VALUES (257, '丰通快运', 'ftky365');
INSERT INTO `express` VALUES (258, 'ZTE中兴物流', 'zteexpress');
INSERT INTO `express` VALUES (259, '鹏远国际速递', 'pegyuaexpress');
INSERT INTO `express` VALUES (260, '中运全速', 'topspeedex');
INSERT INTO `express` VALUES (261, '天翼快递', 'tykd');
INSERT INTO `express` VALUES (262, '远成快运', 'ycgky');
INSERT INTO `express` VALUES (263, '家家通快递', 'ewsway');
INSERT INTO `express` VALUES (264, '安信达', 'axidakuaixi');
INSERT INTO `express` VALUES (265, '能达速递', 'gazhogegda');
INSERT INTO `express` VALUES (266, '佳吉快递', 'jiajikuaidi');
INSERT INTO `express` VALUES (267, '传喜物流', 'chuaxiwuliu');
INSERT INTO `express` VALUES (268, '一号线', 'lieoe');
INSERT INTO `express` VALUES (269, '三象速递', 'sxexpress');
INSERT INTO `express` VALUES (270, '瑞典（Swede Post）', 'ruidiayouzheg');
INSERT INTO `express` VALUES (271, '久久物流', 'jiujiuwl');
INSERT INTO `express` VALUES (272, '星云速递', 'ebuex');
INSERT INTO `express` VALUES (273, '上大物流', 'shagda');
INSERT INTO `express` VALUES (274, '天翼物流', 'tywl99');
INSERT INTO `express` VALUES (275, '星空国际', 'wlwex');
INSERT INTO `express` VALUES (276, '新加坡小包(Sigapore Post)', 'sigpost');
INSERT INTO `express` VALUES (277, 'airpak expresss', 'airpak');
INSERT INTO `express` VALUES (278, '晟邦物流', 'ajigshegbag');
INSERT INTO `express` VALUES (279, '百腾物流', 'baitegwuliu');
INSERT INTO `express` VALUES (280, 'GTS快递', 'gts');
INSERT INTO `express` VALUES (281, 'TRAKPAK', 'trakpak');
INSERT INTO `express` VALUES (282, '签收快递', 'sigedexpress');
INSERT INTO `express` VALUES (283, '远成物流', 'yuachegwuliu');
INSERT INTO `express` VALUES (284, '配思货运', 'peisihuoyukuaidi');
INSERT INTO `express` VALUES (285, '飞豹快递', 'feibaokuaidi');
INSERT INTO `express` VALUES (286, '承诺达', 'ytcheguoda');
INSERT INTO `express` VALUES (287, '顺达快递', 'sudarexpress');
INSERT INTO `express` VALUES (288, '中粮鲜到家物流', 'zlxdjwl');
INSERT INTO `express` VALUES (289, '华夏货运', 'huaxiahuoyu');
INSERT INTO `express` VALUES (290, '佳成快递 ', 'jiacheg');
INSERT INTO `express` VALUES (291, '民航快递', 'mighagkuaidi');
INSERT INTO `express` VALUES (292, '大洋物流', 'dayagwuliu');
INSERT INTO `express` VALUES (293, '安捷物流', 'ajie88');
INSERT INTO `express` VALUES (294, '货运皇', 'kigfreight');
INSERT INTO `express` VALUES (295, 'wedepot物流', 'wedepot');
INSERT INTO `express` VALUES (296, 'GSM', 'gsm');
INSERT INTO `express` VALUES (297, '乌克兰邮政包裹', 'ukrpostc');
INSERT INTO `express` VALUES (298, '万家康物流', 'wjkwl');
INSERT INTO `express` VALUES (299, '魔速达', 'mosuda');
INSERT INTO `express` VALUES (300, '菲律宾（Philippie Postal）', 'phlpost');
INSERT INTO `express` VALUES (301, 'SYNSHIP快递', 'syship');
INSERT INTO `express` VALUES (302, '加佳物流', 'jiajiawl');
INSERT INTO `express` VALUES (303, '英超物流', 'yigchao');
INSERT INTO `express` VALUES (304, '智通物流', 'ztog');
INSERT INTO `express` VALUES (305, '高捷快运', 'goldjet');
INSERT INTO `express` VALUES (306, '海红网送', 'haihogwagsog');
INSERT INTO `express` VALUES (307, 'Asedia USA', 'asediausa');
INSERT INTO `express` VALUES (308, '众川国际', 'zhogchua');
INSERT INTO `express` VALUES (309, '启邦国际物流', 'keypo');
INSERT INTO `express` VALUES (310, '林道国际快递', 'shlidao');
INSERT INTO `express` VALUES (311, '春风物流', 'sprig56');
INSERT INTO `express` VALUES (312, '中天万运', 'zhogtiawayu');
INSERT INTO `express` VALUES (313, '佳辰国际速递', 'jiacheexpress');
INSERT INTO `express` VALUES (314, '亚风速递', 'yafegsudi');
INSERT INTO `express` VALUES (315, '喀麦隆(CAMPOST)', 'cameroo');
INSERT INTO `express` VALUES (316, '中邮电商', 'chiapostcb');
INSERT INTO `express` VALUES (317, 'dhl小包', 'dhlecommerce');
INSERT INTO `express` VALUES (318, '黑猫速运', 'heimao56');
INSERT INTO `express` VALUES (319, '北京EMS', 'bjemstckj');
INSERT INTO `express` VALUES (320, '创一快递', 'chuagyi');
INSERT INTO `express` VALUES (321, 'BHT', 'bht');
INSERT INTO `express` VALUES (322, 'OTrac', 'otrac');
INSERT INTO `express` VALUES (323, '五六快运', 'wuliuky');
INSERT INTO `express` VALUES (324, '鑫世锐达', 'xsrd');
INSERT INTO `express` VALUES (325, '易达通', 'yidatog');
INSERT INTO `express` VALUES (326, 'MoreLik', 'morelik56');
INSERT INTO `express` VALUES (327, '卡塔尔（Qatar Post）', 'qpost');
INSERT INTO `express` VALUES (328, '顺邦国际物流', 'shubag');
INSERT INTO `express` VALUES (329, '西游寄', 'xiyoug');
INSERT INTO `express` VALUES (330, '台湾（中华邮政）', 'postserv');
INSERT INTO `express` VALUES (331, '飞力士物流', 'flysma');
INSERT INTO `express` VALUES (332, '海淘物流', 'ht22');
INSERT INTO `express` VALUES (333, '新加坡EMS、大包(Sigapore Speedpost)', 'speedpost');
INSERT INTO `express` VALUES (334, '爱尔兰(A Post)', 'aposte');
INSERT INTO `express` VALUES (335, '成都东骏物流', 'dogju');
INSERT INTO `express` VALUES (336, '三态速递', 'sataisudi');
INSERT INTO `express` VALUES (337, '好来运', 'hlyex');
INSERT INTO `express` VALUES (338, 'AOL澳通速递', 'aolau');
INSERT INTO `express` VALUES (339, '诚和通', 'cht361');
INSERT INTO `express` VALUES (340, '泛远国际物流', 'farlogistis');
INSERT INTO `express` VALUES (341, '急先达', 'jixiada');
INSERT INTO `express` VALUES (342, '荷兰速递(Nederlad Post)', 'ederladpost');
INSERT INTO `express` VALUES (343, '优海国际速递', 'uhi');
INSERT INTO `express` VALUES (344, '臣邦同城', 'wto56kj');
INSERT INTO `express` VALUES (345, '成达国际速递', 'chegda');
INSERT INTO `express` VALUES (346, 'EMS物流', 'emswuliu');
INSERT INTO `express` VALUES (347, '飞邦快递', 'fbkd');
INSERT INTO `express` VALUES (348, '飞康达', 'feikagda');
INSERT INTO `express` VALUES (349, '科捷物流', 'kejie');
INSERT INTO `express` VALUES (350, '荷兰包裹(PostNL Iteratioal Parcels)', 'postlpacle');
INSERT INTO `express` VALUES (351, '澳通华人物流', 'cllexpress');
INSERT INTO `express` VALUES (352, '海中转运', 'haizhogzhuayu');
INSERT INTO `express` VALUES (353, '中国香港(HogKog Post)英文', 'hkposte');
INSERT INTO `express` VALUES (354, 'E通速递', 'etog');
INSERT INTO `express` VALUES (355, '7号速递', 'express7th');
INSERT INTO `express` VALUES (356, '快捷快物流', 'gdkjk56');
INSERT INTO `express` VALUES (357, '天天快物流', 'guoeryue');
INSERT INTO `express` VALUES (358, '马来西亚小包（Malaysia Post(Registered)）', 'malaysiapost');
INSERT INTO `express` VALUES (359, '美国快递', 'meiguokuaidi');
INSERT INTO `express` VALUES (360, '新西兰中通', 'zzto');
INSERT INTO `express` VALUES (361, 'PCA Express', 'pcaexpress');
INSERT INTO `express` VALUES (362, '邮邦国际', 'youba');
INSERT INTO `express` VALUES (363, '安世通快递', 'astexpress');
INSERT INTO `express` VALUES (364, '邦送物流', 'bagsogwuliu');
INSERT INTO `express` VALUES (365, '上海航瑞货运', 'hagrui');
INSERT INTO `express` VALUES (366, '日本郵便', 'japapost');
INSERT INTO `express` VALUES (367, '捷安达', 'jieada');
INSERT INTO `express` VALUES (368, '渥途国际速运', 'wotu');
INSERT INTO `express` VALUES (369, '迅速快递', 'xusuexpress');
INSERT INTO `express` VALUES (370, '河北橙配', 'chegpei');
INSERT INTO `express` VALUES (371, 'track-parcel', 'trackparcel');
INSERT INTO `express` VALUES (372, '如家国际快递', 'homecourier');
INSERT INTO `express` VALUES (373, '泰国（Thailad Thai Post）', 'thailad');
INSERT INTO `express` VALUES (374, '直德邮', 'zdepost');
INSERT INTO `express` VALUES (375, '贝业物流', 'boyol');
INSERT INTO `express` VALUES (376, '嘉里大荣物流', 'kerrytj');
INSERT INTO `express` VALUES (377, '启辰国际速递', 'qiche');
INSERT INTO `express` VALUES (378, '顺捷丰达', 'shujiefegda');
INSERT INTO `express` VALUES (379, 'ADP国际快递', 'adp');
INSERT INTO `express` VALUES (380, '嘉诚速达', 'jcsuda');
INSERT INTO `express` VALUES (381, '明辉物流', 'zsmhwl');
INSERT INTO `express` VALUES (382, '皮牙子快递', 'bazirim');
INSERT INTO `express` VALUES (383, 'BlueDart', 'bluedart');
INSERT INTO `express` VALUES (384, '泰国中通CTO', 'ctoexp');
INSERT INTO `express` VALUES (385, '俄顺达', 'eshuda');
INSERT INTO `express` VALUES (386, '易优包裹', 'eupackage');
INSERT INTO `express` VALUES (387, '红远物流', 'hogywl');
INSERT INTO `express` VALUES (388, '陆本速递 LUBEN EXPRESS', 'lube');
INSERT INTO `express` VALUES (389, '雪域易购', 'qhxyyg');
INSERT INTO `express` VALUES (390, 'skyet', 'skyet');
INSERT INTO `express` VALUES (391, '青岛安捷快递', 'ajiekuaidi');
INSERT INTO `express` VALUES (392, '加拿大邮政', 'capostfr');
INSERT INTO `express` VALUES (393, '一智通', '1zito');
INSERT INTO `express` VALUES (394, '奔腾物流', 'beteg');
INSERT INTO `express` VALUES (395, 'CCES/国通快递', 'cces');
INSERT INTO `express` VALUES (396, '中骅物流', 'chughwa56');
INSERT INTO `express` VALUES (397, '递四方澳洲', 'disifagau');
INSERT INTO `express` VALUES (398, 'EASY EXPRESS', 'easyexpress');
INSERT INTO `express` VALUES (399, '华瀚快递', 'hhair56');
INSERT INTO `express` VALUES (400, '捷邦物流', 'jiebore');
INSERT INTO `express` VALUES (401, '马来西亚大包、EMS（Malaysia Post(parcel,EMS)）', 'malaysiaems');
INSERT INTO `express` VALUES (402, '猛犸速递', 'mmlogi');
INSERT INTO `express` VALUES (403, '丹麦(Post Demark)', 'postdamarke');
INSERT INTO `express` VALUES (404, 'USPSCN', 'uspsc');
INSERT INTO `express` VALUES (405, '维普恩物流', 'vps');
INSERT INTO `express` VALUES (406, '51跨境通', 'wykjt');
INSERT INTO `express` VALUES (407, '美国云达', 'yudaexus');
INSERT INTO `express` VALUES (408, '澳速物流', 'aosu');
INSERT INTO `express` VALUES (409, '澳货通', 'auex');
INSERT INTO `express` VALUES (410, 'DCS', 'dcs');
INSERT INTO `express` VALUES (411, '波兰小包(Poczta Polska)', 'emoitorig');
INSERT INTO `express` VALUES (412, 'E速达', 'exsuda');
INSERT INTO `express` VALUES (413, '丰羿', 'fegyee');
INSERT INTO `express` VALUES (414, 'LaserShip', 'lasership');
INSERT INTO `express` VALUES (415, '加拿大龙行速运', 'logcps');
INSERT INTO `express` VALUES (416, 'MyHermes', 'myhermes');
INSERT INTO `express` VALUES (417, '斯洛文尼亚(Sloveia Post)', 'sloveia');
INSERT INTO `express` VALUES (418, '新速航', 'suspeedy');
INSERT INTO `express` VALUES (419, '联运通物流', 'szuem');
INSERT INTO `express` VALUES (420, '深圳邮政', 'szyouzheg');
INSERT INTO `express` VALUES (421, '玥玛速运', 'yue777');
INSERT INTO `express` VALUES (422, '比利时国际(Bpost iteratioal)', 'bpostiter');
INSERT INTO `express` VALUES (423, '保加利亚（Bulgaria Posts）', 'bulgaria');
INSERT INTO `express` VALUES (424, 'Chroopost Portugal', 'chroopostport');
INSERT INTO `express` VALUES (425, 'CNAIR', 'cair');
INSERT INTO `express` VALUES (426, '日日顺智慧物联', 'gooday365');
INSERT INTO `express` VALUES (427, '海联快递', 'hltop');
INSERT INTO `express` VALUES (428, 'jcex', 'jcex');
INSERT INTO `express` VALUES (429, '尼尔快递', 'ell');
INSERT INTO `express` VALUES (430, '丰程物流', 'sccod');
INSERT INTO `express` VALUES (431, 'TNT UK', 'ttuk');
INSERT INTO `express` VALUES (432, '越丰物流', 'yuefegwuliu');
INSERT INTO `express` VALUES (433, '运通中港', 'yutogkuaidi');
INSERT INTO `express` VALUES (434, '中环转运', 'zhoghuaus');
INSERT INTO `express` VALUES (435, 'ABF', 'abf');
INSERT INTO `express` VALUES (436, '心怡物流', 'alog');
INSERT INTO `express` VALUES (437, '八达通', 'bdatog');
INSERT INTO `express` VALUES (438, '百通物流', 'buytog');
INSERT INTO `express` VALUES (439, '速舟物流', 'cspeedster');
INSERT INTO `express` VALUES (440, '安的快递', 'gda');
INSERT INTO `express` VALUES (441, '合心速递', 'hexiexpress');
INSERT INTO `express` VALUES (442, 'Highsice', 'highsice');
INSERT INTO `express` VALUES (443, '飞鹰物流', 'hfy');
INSERT INTO `express` VALUES (444, '皇家云仓', 'hotwms');
INSERT INTO `express` VALUES (445, '中国香港环球快运', 'huaqiuabc');
INSERT INTO `express` VALUES (446, '全速物流', 'quasu');
INSERT INTO `express` VALUES (447, '银捷速递', 'yijiesudi');
INSERT INTO `express` VALUES (448, '东风快递', 'dfkuaidi');
INSERT INTO `express` VALUES (449, 'DHL HK', 'dhlhk');
INSERT INTO `express` VALUES (450, '店通快递', 'diatogkuaidi');
INSERT INTO `express` VALUES (451, 'FOX国际快递', 'fox');
INSERT INTO `express` VALUES (452, '德尚国际速递', 'gslexpress');
INSERT INTO `express` VALUES (453, '秦邦快运', 'qbexpress');
INSERT INTO `express` VALUES (454, '圣安物流', 'shegawuliu');
INSERT INTO `express` VALUES (455, '红马甲物流', 'sxhogmajia');
INSERT INTO `express` VALUES (456, '祥龙运通物流', 'xiaglogyutog');
INSERT INTO `express` VALUES (457, '宇佳物流', 'yujiawl');
INSERT INTO `express` VALUES (458, '准实快运', 'zsky123');
INSERT INTO `express` VALUES (459, '泰捷达国际物流', 'ztjieda');
INSERT INTO `express` VALUES (460, '航空快递', 'airgtc');
INSERT INTO `express` VALUES (461, '蜜蜂速递', 'bee001');
INSERT INTO `express` VALUES (462, '凡宇快递', 'fayukuaidi');
INSERT INTO `express` VALUES (463, 'Hermes', 'hermes');
INSERT INTO `express` VALUES (464, '华企快运', 'huaqikuaiyu');
INSERT INTO `express` VALUES (465, '牙买加（Jamaica Post）', 'jamaicapost');
INSERT INTO `express` VALUES (466, '楽道物流', 'ledaowuliu');
INSERT INTO `express` VALUES (467, '明亮物流', 'migliagwuliu');
INSERT INTO `express` VALUES (468, '全际通', 'quajitog');
INSERT INTO `express` VALUES (469, '日日顺快线', 'rrskx');
INSERT INTO `express` VALUES (470, '赛澳递for买卖宝', 'saiaodimmb');
INSERT INTO `express` VALUES (471, 'wish邮', 'shpostwish');
INSERT INTO `express` VALUES (472, '特急便物流', 'sucmj');
INSERT INTO `express` VALUES (473, '瑞士(Swiss Post)', 'swisspost');
INSERT INTO `express` VALUES (474, 'YDH', 'ydhex');
INSERT INTO `express` VALUES (475, '一运全成物流', 'yyqc56');
INSERT INTO `express` VALUES (476, 'A2U速递', 'a2u');
INSERT INTO `express` VALUES (477, '德方物流', 'ahdf');
INSERT INTO `express` VALUES (478, '展勤快递', 'byht');
INSERT INTO `express` VALUES (479, '能装能送', 'cahold');
INSERT INTO `express` VALUES (480, 'City-Lik', 'citylik');
INSERT INTO `express` VALUES (481, '城晓国际快递', 'ckeex');
INSERT INTO `express` VALUES (482, '叮咚快递', 'digdog');
INSERT INTO `express` VALUES (483, 'DPD UK', 'dpduk');
INSERT INTO `express` VALUES (484, '飞快达', 'feikuaida');
INSERT INTO `express` VALUES (485, '凤凰快递', 'feghuagkuaidi');
INSERT INTO `express` VALUES (486, 'globaltracktrace', 'globaltracktrace');
INSERT INTO `express` VALUES (487, '高铁速递', 'hre');
INSERT INTO `express` VALUES (488, '爱拜物流', 'ibuy8');
INSERT INTO `express` VALUES (489, '大达物流', 'idada');
INSERT INTO `express` VALUES (490, '金大物流', 'jidawuliu');
INSERT INTO `express` VALUES (491, 'KCS', 'kcs');
INSERT INTO `express` VALUES (492, 'Ladmark Global', 'ladmarkglobal');
INSERT INTO `express` VALUES (493, '6LS EXPRESS', 'lsexpress');
INSERT INTO `express` VALUES (494, '吉捷国际速递', 'luckyfastex');
INSERT INTO `express` VALUES (495, 'LWE', 'lwe');
INSERT INTO `express` VALUES (496, '中国澳门(Macau Post)', 'macao');
INSERT INTO `express` VALUES (497, '木春货运', 'mchy');
INSERT INTO `express` VALUES (498, '皇家物流', 'pfcexpress');
INSERT INTO `express` VALUES (499, '赛澳递', 'saiaodi');
INSERT INTO `express` VALUES (500, '中外运空运', 'sioairiex');
INSERT INTO `express` VALUES (501, '世华通物流', 'szshihuatog56');
INSERT INTO `express` VALUES (502, '明达国际速递', 'tmwexpress');
INSERT INTO `express` VALUES (503, 'Toll Priority(Toll Olie)', 'tollpriority');
INSERT INTO `express` VALUES (504, '通和天下', 'toghetiaxia');
INSERT INTO `express` VALUES (505, '新元快递', 'xigyuakuaidi');
INSERT INTO `express` VALUES (506, '新宁物流', 'xiig');
INSERT INTO `express` VALUES (507, '易欧洲国际物流', 'yiouzhou');
INSERT INTO `express` VALUES (508, '三三国际物流', 'zeze');
INSERT INTO `express` VALUES (509, '中技物流', 'zhogjiwuliu');
INSERT INTO `express` VALUES (510, '众派速递', 'zhpex');
INSERT INTO `express` VALUES (511, '振捷国际货运', 'zjgj56');
INSERT INTO `express` VALUES (512, '安达信', 'advacig');
INSERT INTO `express` VALUES (513, 'Aplus物流', 'aplusex');
INSERT INTO `express` VALUES (514, '艾瑞斯远', 'ariesfar');
INSERT INTO `express` VALUES (515, '澳邦国际物流', 'ausbodexpress');
INSERT INTO `express` VALUES (516, '比利时(Belgium Post)', 'belgiumpost');
INSERT INTO `express` VALUES (517, '同舟行物流', 'chiatzx');
INSERT INTO `express` VALUES (518, 'C&C国际速递', 'ccexp');
INSERT INTO `express` VALUES (519, '中欧物流', 'ceulogistics');
INSERT INTO `express` VALUES (520, '大道物流', 'dadaoex');
INSERT INTO `express` VALUES (521, '深圳德创物流', 'dechuagwuliu');
INSERT INTO `express` VALUES (522, 'DPD Polad', 'dpdpolad');
INSERT INTO `express` VALUES (523, '澳州顺风快递', 'emms');
INSERT INTO `express` VALUES (524, '澳洲新干线快递', 'expressplus');
INSERT INTO `express` VALUES (525, '加拿大联通快运', 'fastotime');
INSERT INTO `express` VALUES (526, '飞狐快递', 'feihukuaidi');
INSERT INTO `express` VALUES (527, 'GHT物流', 'ghtexpress');
INSERT INTO `express` VALUES (528, '驿扬国际速运', 'iyougspeed');
INSERT INTO `express` VALUES (529, '晋越快递', 'jiyuekuaidi');
INSERT INTO `express` VALUES (530, '考拉国际速递', 'kaolaexpress');
INSERT INTO `express` VALUES (531, '快速递', 'ksudi');
INSERT INTO `express` VALUES (532, '俄罗斯邮政(Russia Post)', 'pochta');
INSERT INTO `express` VALUES (533, '全信通快递', 'quaxitog');
INSERT INTO `express` VALUES (534, '日昱物流', 'riyuwuliu');
INSERT INTO `express` VALUES (535, 'Safexpress', 'safexpress');
INSERT INTO `express` VALUES (536, '首达速运', 'sdsy888');
INSERT INTO `express` VALUES (537, '顺通快递', 'stkd');
INSERT INTO `express` VALUES (538, '泰国中通ZTO', 'thaizto');
INSERT INTO `express` VALUES (539, '乌克兰小包、大包(UkrPost)', 'ukrpost');
INSERT INTO `express` VALUES (540, 'UPS Freight', 'upsfreight');
INSERT INTO `express` VALUES (541, '一辉物流', 'yatfai');
INSERT INTO `express` VALUES (542, '一起送', 'yiqisog');
INSERT INTO `express` VALUES (543, '宜送', 'yisog');
INSERT INTO `express` VALUES (544, '纵通速运', 'yztsy');
INSERT INTO `express` VALUES (545, '永昌物流', 'yogchagwuliu');
INSERT INTO `express` VALUES (546, '元智捷诚', 'yuazhijiecheg');
INSERT INTO `express` VALUES (547, '珠峰速运', 'zf365');
INSERT INTO `express` VALUES (548, '中外运速递', 'zhogwaiyu');
INSERT INTO `express` VALUES (549, '增速跨境 ', 'zyzoom');
INSERT INTO `express` VALUES (550, '全球快运', 'abcglobal');
INSERT INTO `express` VALUES (551, '卡邦配送', 'ahkbps');
INSERT INTO `express` VALUES (552, '捷记方舟', 'ajexpress');
INSERT INTO `express` VALUES (553, '阿尔巴尼亚(Posta shqipatre)', 'albaia');
INSERT INTO `express` VALUES (554, '无忧物流', 'aliexpress');
INSERT INTO `express` VALUES (555, 'amazo-国内订单', 'amcorder');
INSERT INTO `express` VALUES (556, '新干线快递', 'alexpress');
INSERT INTO `express` VALUES (557, '阿鲁巴[荷兰],（Post Aruba）', 'aruba');
INSERT INTO `express` VALUES (558, '澳世速递', 'ausexpress');
INSERT INTO `express` VALUES (559, '奥地利(Austria Post)', 'austria');
INSERT INTO `express` VALUES (560, '中联速递', 'auvada');
INSERT INTO `express` VALUES (561, '百世云配', 'baishiyp');
INSERT INTO `express` VALUES (562, '宝通快递', 'baotogkd');
INSERT INTO `express` VALUES (563, '白俄罗斯(Belpochta)', 'belpost');
INSERT INTO `express` VALUES (564, '飛斯特', 'bester');
INSERT INTO `express` VALUES (565, '青云物流', 'bjqywl');
INSERT INTO `express` VALUES (566, '鑫锐达', 'bjxsrd');
INSERT INTO `express` VALUES (567, '河南次晨达', 'ccd');
INSERT INTO `express` VALUES (568, '城铁速递', 'cex');
INSERT INTO `express` VALUES (569, '城际快递', 'chegji');
INSERT INTO `express` VALUES (570, 'SQK国际速递', 'chiasqk');
INSERT INTO `express` VALUES (571, '邦通国际', 'comexpress');
INSERT INTO `express` VALUES (572, '重庆星程快递', 'cqxigcheg');
INSERT INTO `express` VALUES (573, '德中快递', 'declh');
INSERT INTO `express` VALUES (574, 'Deltec Courier', 'deltec');
INSERT INTO `express` VALUES (575, '东方航空物流', 'ealceair');
INSERT INTO `express` VALUES (576, 'ECMS Express', 'ecmsglobal');
INSERT INTO `express` VALUES (577, '联众国际', 'epspost');
INSERT INTO `express` VALUES (578, '埃塞俄比亚(Ethiopia postal)', 'ethiopia');
INSERT INTO `express` VALUES (579, 'EU-EXPRESS', 'euexpress');
INSERT INTO `express` VALUES (580, 'europeaecom', 'europeaecom');
INSERT INTO `express` VALUES (581, '可可树美中速运', 'excocotree');
INSERT INTO `express` VALUES (582, 'FedEx-英国件（FedEx UK)', 'fedexuk');
INSERT INTO `express` VALUES (583, '芬兰(Itella Posti Oy)', 'filad');
INSERT INTO `express` VALUES (584, '花瓣转运', 'flowerkd');
INSERT INTO `express` VALUES (585, '全速快递', 'fsexp');
INSERT INTO `express` VALUES (586, '高铁快运', 'gaotieex');
INSERT INTO `express` VALUES (587, '容智快运', 'gdrz58');
INSERT INTO `express` VALUES (588, '直布罗陀[英国],( Royal Gibraltar Post)', 'gibraltar');
INSERT INTO `express` VALUES (589, '共速达', 'gogsuda');
INSERT INTO `express` VALUES (590, '广通速递', 'gtogsudi');
INSERT INTO `express` VALUES (591, 'GTT EXPRESS快递', 'gttexpress');
INSERT INTO `express` VALUES (592, '广东通路', 'guagdogtoglu');
INSERT INTO `express` VALUES (593, '航宇快递', 'hagyu');
INSERT INTO `express` VALUES (594, '好又快物流', 'haoyoukuai');
INSERT INTO `express` VALUES (595, '开心快递', 'happylik');
INSERT INTO `express` VALUES (596, '华美快递', 'hmus');
INSERT INTO `express` VALUES (597, '河南全速通', 'hqst');
INSERT INTO `express` VALUES (598, '居家通', 'homexpress');
INSERT INTO `express` VALUES (599, '宏品物流', 'hogpiwuliu');
INSERT INTO `express` VALUES (600, '华达快运', 'huada');
INSERT INTO `express` VALUES (601, '恒宇运通', 'hyytes');
INSERT INTO `express` VALUES (602, '多米尼加（INPOSDOM – Istituto Postal Domiicao）', 'iposdom');
INSERT INTO `express` VALUES (603, 'Italy SDA', 'italysad');
INSERT INTO `express` VALUES (604, '骏达快递', 'jdexpressusa');
INSERT INTO `express` VALUES (605, 'JDIEX', 'jdiex');
INSERT INTO `express` VALUES (606, '加州猫速递', 'jiazhoumao');
INSERT INTO `express` VALUES (607, '聚鼎物流', 'judig');
INSERT INTO `express` VALUES (608, '骏丰国际速递', 'jufegguoji');
INSERT INTO `express` VALUES (609, '韩国邮政', 'koreapostc');
INSERT INTO `express` VALUES (610, '淘韩国际快递', 'krtao');
INSERT INTO `express` VALUES (611, '快8速运', 'kuai8');
INSERT INTO `express` VALUES (612, '隆浪快递', 'loglagkuaidi');
INSERT INTO `express` VALUES (613, '鲁通快运', 'lutog');
INSERT INTO `express` VALUES (614, '澳洲迈速快递', 'maxeedexpress');
INSERT INTO `express` VALUES (615, '民邦速递', 'mibagsudi');
INSERT INTO `express` VALUES (616, '牛仔速运', 'iuzaiexpress');
INSERT INTO `express` VALUES (617, '华赫物流', 'mhuahe');
INSERT INTO `express` VALUES (618, '腾达速递', 'tegda');
INSERT INTO `express` VALUES (619, '英国邮政大包EMS', 'parcelforcec');
INSERT INTO `express` VALUES (620, '派尔快递', 'peex');
INSERT INTO `express` VALUES (621, '秘鲁(SERPOST)', 'peru');
INSERT INTO `express` VALUES (622, '土耳其', 'ptt');
INSERT INTO `express` VALUES (623, '急顺通', 'pzhjst');
INSERT INTO `express` VALUES (624, '千里速递', 'qiali');
INSERT INTO `express` VALUES (625, '全川物流', 'quachua56');
INSERT INTO `express` VALUES (626, '全通快运', 'quatwl');
INSERT INTO `express` VALUES (627, 'rpx', 'rpx');
INSERT INTO `express` VALUES (628, 'S2C', 's2c');
INSERT INTO `express` VALUES (629, '三盛快递', 'sashegco');
INSERT INTO `express` VALUES (630, '十方通物流', 'sfift');
INSERT INTO `express` VALUES (631, '圣飞捷快递', 'sfjhd');
INSERT INTO `express` VALUES (632, '上海快通', 'shaghaikuaitog');
INSERT INTO `express` VALUES (633, '盛通快递', 'shegtogscm');
INSERT INTO `express` VALUES (634, 'SHL畅灵国际物流', 'shlexp');
INSERT INTO `express` VALUES (635, '顺捷达', 'shujieda');
INSERT INTO `express` VALUES (636, '穗佳物流', 'suijiawuliu');
INSERT INTO `express` VALUES (637, '泰进物流', 'taiji');
INSERT INTO `express` VALUES (638, '天纵物流', 'tiazog');
INSERT INTO `express` VALUES (639, '乌干达(Posta Ugada)', 'ugada');
INSERT INTO `express` VALUES (640, '邮鸽速运', 'ugoexpress');
INSERT INTO `express` VALUES (641, '万庚国际速递', 'vageexpress');
INSERT INTO `express` VALUES (642, '越中国际物流', 'vctras');
INSERT INTO `express` VALUES (643, '越南EMS(VNPost Express)', 'vpost');
INSERT INTO `express` VALUES (644, '豌豆物流', 'wadougogzhu');
INSERT INTO `express` VALUES (645, '文捷航空', 'wejiesudi');
INSERT INTO `express` VALUES (646, '蓝天物流', 'xflt56');
INSERT INTO `express` VALUES (647, '湘达物流', 'xiagdawuliu');
INSERT INTO `express` VALUES (648, '翔腾物流', 'xiagteg');
INSERT INTO `express` VALUES (649, '亚马逊中国', 'yamaxuwuliu');
INSERT INTO `express` VALUES (650, '云达通', 'ydglobe');
INSERT INTO `express` VALUES (651, '宜送物流', 'yiex');
INSERT INTO `express` VALUES (652, '艺凡快递', 'yifakd');
INSERT INTO `express` VALUES (653, '亿领速运', 'yiligsuyu');
INSERT INTO `express` VALUES (654, 'YODEL', 'yodel');
INSERT INTO `express` VALUES (655, '邮来速递', 'youlai');
INSERT INTO `express` VALUES (656, '雅澳物流', 'yourscm');
INSERT INTO `express` VALUES (657, '众辉达物流', 'zhdwl');
INSERT INTO `express` VALUES (658, '忠信达', 'zhogxida');
INSERT INTO `express` VALUES (659, '卓实快运', 'zhuoshikuaiyu');
INSERT INTO `express` VALUES (660, '转瞬达集运', 'zsda56');
INSERT INTO `express` VALUES (661, '中远快运', 'zy100');
INSERT INTO `express` VALUES (662, '明大快递', 'adaexpress');
INSERT INTO `express` VALUES (663, '安达易国际速递', 'adiexpress');
INSERT INTO `express` VALUES (664, '德国雄鹰速递', 'adlerlogi');
INSERT INTO `express` VALUES (665, '阿富汗(Afgha Post)', 'afgha');
INSERT INTO `express` VALUES (666, 'AFL', 'afl');
INSERT INTO `express` VALUES (667, '全程快递', 'agopost');
INSERT INTO `express` VALUES (668, '澳捷物流', 'ajlogistics');
INSERT INTO `express` VALUES (669, '亚马逊中国订单', 'amazocorder');
INSERT INTO `express` VALUES (670, 'amazo-国际订单', 'amusorder');
INSERT INTO `express` VALUES (671, '安家同城快运', 'ajiatogcheg');
INSERT INTO `express` VALUES (672, 'apgecommerce', 'apgecommerce');
INSERT INTO `express` VALUES (673, '美国汉邦快递', 'aplus100');
INSERT INTO `express` VALUES (674, 'AUV国际快递', 'auvexpress');
INSERT INTO `express` VALUES (675, '澳新物流', 'axexpress');
INSERT INTO `express` VALUES (676, '阿塞拜疆EMS(EMS AzerExpressPost)', 'azerbaija');
INSERT INTO `express` VALUES (677, '巴林(Bahrai Post)', 'bahrai');
INSERT INTO `express` VALUES (678, '帮帮发', 'bagbagpost');
INSERT INTO `express` VALUES (679, '孟加拉国(EMS)', 'bagladesh');
INSERT INTO `express` VALUES (680, '报通快递', 'baoxiada');
INSERT INTO `express` VALUES (681, '巴巴多斯(Barbados Post)', 'barbados');
INSERT INTO `express` VALUES (682, 'BCWELT', 'bcwelt');
INSERT INTO `express` VALUES (683, '伯利兹(Belize Postal)', 'belize');
INSERT INTO `express` VALUES (684, '笨鸟国际', 'beiao');
INSERT INTO `express` VALUES (685, '彪记快递', 'biaojikuaidi');
INSERT INTO `express` VALUES (686, '佰乐捷通', 'bljt56');
INSERT INTO `express` VALUES (687, '标杆物流', 'bmlchia');
INSERT INTO `express` VALUES (688, '波黑(JP BH Posta)', 'bohei');
INSERT INTO `express` VALUES (689, '玻利维亚', 'bolivia');
INSERT INTO `express` VALUES (690, 'BorderGuru', 'borderguru');
INSERT INTO `express` VALUES (691, '堡昕德速递', 'bosid');
INSERT INTO `express` VALUES (692, '博茨瓦纳', 'botspost');
INSERT INTO `express` VALUES (693, '速方(Sufast)', 'bphchia');
INSERT INTO `express` VALUES (694, '百千诚物流', 'bqcwl');
INSERT INTO `express` VALUES (695, '巴西(Brazil Post/Correios)', 'brazilposte');
INSERT INTO `express` VALUES (696, '文莱(Bruei Postal)', 'bruei');
INSERT INTO `express` VALUES (697, '新喀里多尼亚[法国],(New Caledoia)', 'caledoia');
INSERT INTO `express` VALUES (698, '柬埔寨(Cambodia Post)', 'cambodia');
INSERT INTO `express` VALUES (699, '到了港', 'camekog');
INSERT INTO `express` VALUES (700, 'Campbell’s Express', 'campbellsexpress');
INSERT INTO `express` VALUES (701, '卢森堡航空', 'cargolux');
INSERT INTO `express` VALUES (702, '钏博物流', 'cbo56');
INSERT INTO `express` VALUES (703, '中集冷云', 'cccc58');
INSERT INTO `express` VALUES (704, 'CDEK', 'cdek');
INSERT INTO `express` VALUES (705, '鑫宸物流', 'cdxiche56');
INSERT INTO `express` VALUES (706, '捷克（?eská po?ta）', 'ceskaposta');
INSERT INTO `express` VALUES (707, 'CEVA Logistic', 'cevalogistics');
INSERT INTO `express` VALUES (708, '银雁专送', 'cfss');
INSERT INTO `express` VALUES (709, '昌宇国际', 'chagwooair');
INSERT INTO `express` VALUES (710, '长宇物流', 'chagyuwuliu');
INSERT INTO `express` VALUES (711, '智利(Correos Chile)', 'chile');
INSERT INTO `express` VALUES (712, '华欣物流', 'chiastarlogistics');
INSERT INTO `express` VALUES (713, '嘉荣物流', 'chllog');
INSERT INTO `express` VALUES (714, '法国大包、EMS-法文（Chroopost Frace）', 'chroopostfra');
INSERT INTO `express` VALUES (715, '法国大包、EMS-英文(Chroopost Frace)', 'chroopostfre');
INSERT INTO `express` VALUES (716, '中国香港骏辉物流', 'chufai');
INSERT INTO `express` VALUES (717, '城市映急', 'city56');
INSERT INTO `express` VALUES (718, 'citysprit', 'citysprit');
INSERT INTO `express` VALUES (719, '大韩通运', 'cjkoreaexpress');
INSERT INTO `express` VALUES (720, 'CE易欧通国际速递', 'cloudexpress');
INSERT INTO `express` VALUES (721, 'CL日中速运', 'clsp');
INSERT INTO `express` VALUES (722, 'CNUP 中联邮', 'cup');
INSERT INTO `express` VALUES (723, '中国翼', 'cws');
INSERT INTO `express` VALUES (724, '哥伦比亚(4-72 La Red Postal de Colombia)', 'colombia');
INSERT INTO `express` VALUES (725, '莫桑比克（Correios de Moçambique）', 'correios');
INSERT INTO `express` VALUES (726, '乌拉圭（Correo Uruguayo）', 'correo');
INSERT INTO `express` VALUES (727, '阿根廷(Correo Argetia)', 'correoargetio');
INSERT INTO `express` VALUES (728, '哥斯达黎加(Correos de Costa Rica)', 'correos');
INSERT INTO `express` VALUES (729, '华中快递', 'cpsair');
INSERT INTO `express` VALUES (730, '环旅快运', 'crossbox');
INSERT INTO `express` VALUES (731, '新时速物流', 'csxss');
INSERT INTO `express` VALUES (732, '塞浦路斯(Cyprus Post)', 'cypruspost');
INSERT INTO `express` VALUES (733, '云南诚中物流', 'czwly');
INSERT INTO `express` VALUES (734, '丹递56', 'dade56');
INSERT INTO `express` VALUES (735, '达速物流', 'dasu');
INSERT INTO `express` VALUES (736, '澳行快递', 'desworks');
INSERT INTO `express` VALUES (737, '达方物流', 'dfpost');
INSERT INTO `express` VALUES (738, 'DHL-荷兰（DHL Netherlads）', 'dhletherlads');
INSERT INTO `express` VALUES (739, 'DHL-波兰（DHL Polad）', 'dhlpolad');
INSERT INTO `express` VALUES (740, '递五方云仓', 'di5pll');
INSERT INTO `express` VALUES (741, '云南滇驿物流', 'diayi');
INSERT INTO `express` VALUES (742, '递达速运', 'didasuyu');
INSERT INTO `express` VALUES (743, '叮咚澳洲转运', 'dido');
INSERT INTO `express` VALUES (744, 'Direct Lik', 'directlik');
INSERT INTO `express` VALUES (745, '递四方美国', 'disifagus');
INSERT INTO `express` VALUES (746, '天翔东捷运', 'djy56');
INSERT INTO `express` VALUES (747, '东瀚物流', 'doghawl');
INSERT INTO `express` VALUES (748, '东红物流', 'doghog');
INSERT INTO `express` VALUES (749, 'DPD Germay', 'dpdgermay');
INSERT INTO `express` VALUES (750, 'DTDC Idia', 'dtdcidia');
INSERT INTO `express` VALUES (751, 'duodao56', 'duodao56');
INSERT INTO `express` VALUES (752, 'E跨通', 'ecalltur');
INSERT INTO `express` VALUES (753, 'EC-Firstclass', 'ecfirstclass');
INSERT INTO `express` VALUES (754, '东西E全运', 'ecotrasite');
INSERT INTO `express` VALUES (755, '厄瓜多尔(Correos del Ecuador)', 'ecuador');
INSERT INTO `express` VALUES (756, '易达快运', 'edaeuexpress');
INSERT INTO `express` VALUES (757, '龙象国际物流', 'edrago');
INSERT INTO `express` VALUES (758, 'e直运', 'edtexpress');
INSERT INTO `express` VALUES (759, 'EFSPOST', 'efspost');
INSERT INTO `express` VALUES (760, '埃及（Egypt Post）', 'egypt');
INSERT INTO `express` VALUES (761, '艾菲尔国际速递', 'eiffel');
INSERT INTO `express` VALUES (762, '易联通达', 'el56');
INSERT INTO `express` VALUES (763, '希腊包裹（ELTA Helleic Post）', 'elta');
INSERT INTO `express` VALUES (764, '希腊EMS（ELTA Courier）', 'eltahell');
INSERT INTO `express` VALUES (765, '阿联酋(Emirates Post)', 'emirates');
INSERT INTO `express` VALUES (766, '南非EMS', 'emssouthafrica');
INSERT INTO `express` VALUES (767, '乌克兰EMS(EMS Ukraie)', 'emsukraie');
INSERT INTO `express` VALUES (768, '乌克兰EMS-中文(EMS Ukraie)', 'emsukraiec');
INSERT INTO `express` VALUES (769, '英国(大包,EMS)', 'eglad');
INSERT INTO `express` VALUES (770, '中外运', 'esiotras');
INSERT INTO `express` VALUES (771, 'Estafeta', 'estafeta');
INSERT INTO `express` VALUES (772, 'Estes', 'estes');
INSERT INTO `express` VALUES (773, '易达国际速递', 'eta100');
INSERT INTO `express` VALUES (774, '中欧国际物流', 'eucrail');
INSERT INTO `express` VALUES (775, '德国 EUC POST', 'eucpost');
INSERT INTO `express` VALUES (776, '易邮国际', 'euguoji');
INSERT INTO `express` VALUES (777, '败欧洲', 'europe8');
INSERT INTO `express` VALUES (778, '优莎速运', 'eusac');
INSERT INTO `express` VALUES (779, '易转运', 'ezhuayua');
INSERT INTO `express` VALUES (780, '颿达国际快递-英文', 'fadaguoji');
INSERT INTO `express` VALUES (781, '颿达国际快递', 'fardarww');
INSERT INTO `express` VALUES (782, 'Fastway Irelad', 'fastway');
INSERT INTO `express` VALUES (783, '正途供应链', 'fastzt');
INSERT INTO `express` VALUES (784, 'FedEx-英国件', 'fedexukc');
INSERT INTO `express` VALUES (785, 'FedRoad 联邦转运', 'fedroad');
INSERT INTO `express` VALUES (786, '斐济(Fiji Post)', 'fiji');
INSERT INTO `express` VALUES (787, 'FQ狂派速递', 'freakyquick');
INSERT INTO `express` VALUES (788, '法翔速运', 'ftlexpress');
INSERT INTO `express` VALUES (789, '飞云快递系统', 'fyex');
INSERT INTO `express` VALUES (790, 'Gati-中文', 'gatic');
INSERT INTO `express` VALUES (791, 'Gati-英文', 'gatie');
INSERT INTO `express` VALUES (792, 'Gati-KWE', 'gatikwe');
INSERT INTO `express` VALUES (793, '广东诚通物流', 'gdct56');
INSERT INTO `express` VALUES (794, '全网物流', 'gdqwwl');
INSERT INTO `express` VALUES (795, '新鹏快递', 'gdxp');
INSERT INTO `express` VALUES (796, 'GE2D跨境物流', 'ge2d');
INSERT INTO `express` VALUES (797, '格鲁吉亚(Georgia Pos）', 'georgiapost');
INSERT INTO `express` VALUES (798, '环创物流', 'ghl');
INSERT INTO `express` VALUES (799, '冠捷物流 ', 'gjwl');
INSERT INTO `express` VALUES (800, 'GLS', 'gls');
INSERT INTO `express` VALUES (801, '英脉物流', 'gml');
INSERT INTO `express` VALUES (802, '格陵兰[丹麦],（TELE Greelad A/S）', 'greelad');
INSERT INTO `express` VALUES (803, '潍鸿', 'grivertek');
INSERT INTO `express` VALUES (804, '哥士传奇速递', 'gscq365');
INSERT INTO `express` VALUES (805, '万通快递', 'gswtkd');
INSERT INTO `express` VALUES (806, 'GT国际快运', 'gtgogo');
INSERT INTO `express` VALUES (807, '冠庭国际物流', 'guatig');
INSERT INTO `express` VALUES (808, '国送快运', 'guosog');
INSERT INTO `express` VALUES (809, '宏观国际快递', 'gvpexpress');
INSERT INTO `express` VALUES (810, '光线速递', 'gxwl');
INSERT INTO `express` VALUES (811, '贵州星程快递', 'gzxigcheg');
INSERT INTO `express` VALUES (812, '海红for买卖宝', 'haihogmmb');
INSERT INTO `express` VALUES (813, '海盟速递', 'haimegsudi');
INSERT INTO `express` VALUES (814, '海外环球', 'haiwaihuaqiu');
INSERT INTO `express` VALUES (815, '海星桥快递', 'haixigqiao');
INSERT INTO `express` VALUES (816, '汉邦国际速递', 'hadboy');
INSERT INTO `express` VALUES (817, '翰丰快递', 'hafegjl');
INSERT INTO `express` VALUES (818, '亚美尼亚(Haypost-Armeia Postal)', 'haypost');
INSERT INTO `express` VALUES (819, '恒瑞物流', 'hegrui56');
INSERT INTO `express` VALUES (820, '环国运物流', 'hgy56');
INSERT INTO `express` VALUES (821, 'Hi淘易快递', 'hitaoe');
INSERT INTO `express` VALUES (822, '猴急送', 'hjs');
INSERT INTO `express` VALUES (823, '互联快运', 'hlkytj');
INSERT INTO `express` VALUES (824, '共联配', 'hlpgyl');
INSERT INTO `express` VALUES (825, '顺时达物流', 'hssd56');
INSERT INTO `express` VALUES (826, '中强物流', 'hzqwl');
INSERT INTO `express` VALUES (827, '红背心', 'hogbeixi');
INSERT INTO `express` VALUES (828, '宏捷国际物流', 'hogjie');
INSERT INTO `express` VALUES (829, '环球通达 ', 'hqtd');
INSERT INTO `express` VALUES (830, '卓烨快递', 'hrbzykd');
INSERT INTO `express` VALUES (831, '克罗地亚（Hrvatska Posta）', 'hrvatska');
INSERT INTO `express` VALUES (832, '海硕高铁速递', 'hsgtsd');
INSERT INTO `express` VALUES (833, '华通快运', 'htogexpress');
INSERT INTO `express` VALUES (834, '华通务达物流', 'htwd');
INSERT INTO `express` VALUES (835, '环东物流', 'huadoglg');
INSERT INTO `express` VALUES (836, '汇强快递', 'huiqiagkuaidi');
INSERT INTO `express` VALUES (837, '驼峰国际', 'humplie');
INSERT INTO `express` VALUES (838, '匈牙利（Magyar Posta）', 'hugary');
INSERT INTO `express` VALUES (839, '兰州伙伴物流', 'huoba');
INSERT INTO `express` VALUES (840, '户通物流', 'hutogwuliu');
INSERT INTO `express` VALUES (841, '鸿远物流', 'hyeship');
INSERT INTO `express` VALUES (842, '上海昊宏国际货物', 'hyk');
INSERT INTO `express` VALUES (843, '华航快递', 'hzpl');
INSERT INTO `express` VALUES (844, '冰岛(Icelad Post)', 'icelad');
INSERT INTO `express` VALUES (845, 'iExpress', 'iexpress');
INSERT INTO `express` VALUES (846, 'loge路坚', 'iloge');
INSERT INTO `express` VALUES (847, 'ILYANG', 'ilyag');
INSERT INTO `express` VALUES (848, '艾姆勒', 'imlb2c');
INSERT INTO `express` VALUES (849, '印度(Idia Post)', 'idia');
INSERT INTO `express` VALUES (850, '印度尼西亚EMS(Pos Idoesia-EMS)', 'idoesia');
INSERT INTO `express` VALUES (851, 'Iterlik Express', 'iterlik');
INSERT INTO `express` VALUES (852, 'UPS i-parcel', 'iparcel');
INSERT INTO `express` VALUES (853, '伊朗（Ira Post）', 'ira');
INSERT INTO `express` VALUES (854, '以色列(Israel Post)', 'israelpost');
INSERT INTO `express` VALUES (855, '急递', 'jdpplus');
INSERT INTO `express` VALUES (856, '泽西岛', 'jerseypost');
INSERT INTO `express` VALUES (857, '澳速通国际速递', 'jetexpressgroup');
INSERT INTO `express` VALUES (858, '佳家通货运', 'jiajiatog56');
INSERT INTO `express` VALUES (859, '锦程物流', 'jichegwuliu');
INSERT INTO `express` VALUES (860, '劲通快递', 'jitogkd');
INSERT INTO `express` VALUES (861, '冀速物流', 'jisu');
INSERT INTO `express` VALUES (862, '九宫物流', 'jiugog');
INSERT INTO `express` VALUES (863, '久易快递', 'jiuyic');
INSERT INTO `express` VALUES (864, '吉祥邮（澳洲）', 'jixiagyouau');
INSERT INTO `express` VALUES (865, '佳捷翔物流', 'jjx888');
INSERT INTO `express` VALUES (866, '约旦(Jorda Post)', 'jorda');
INSERT INTO `express` VALUES (867, '骏绅物流', 'jsexpress');
INSERT INTO `express` VALUES (868, '聚物物流', 'juwu');
INSERT INTO `express` VALUES (869, '聚中大', 'juzhogda');
INSERT INTO `express` VALUES (870, '哈萨克斯坦(Kazpost)', 'kazpost');
INSERT INTO `express` VALUES (871, '肯尼亚(POSTA KENYA)', 'keya');
INSERT INTO `express` VALUES (872, '快服务', 'kfwet');
INSERT INTO `express` VALUES (873, '柬埔寨中通', 'khzto');
INSERT INTO `express` VALUES (874, '跨境直邮通', 'kjde');
INSERT INTO `express` VALUES (875, '番薯国际货运', 'koali');
INSERT INTO `express` VALUES (876, '韩国邮政韩文', 'koreapostkr');
INSERT INTO `express` VALUES (877, '快达物流', 'kuaidawuliu');
INSERT INTO `express` VALUES (878, '快淘快递', 'kuaitao');
INSERT INTO `express` VALUES (879, '四川快优达速递', 'kuaiyouda');
INSERT INTO `express` VALUES (880, '凯信达', 'kxda');
INSERT INTO `express` VALUES (881, '吉尔吉斯斯坦(Kyrgyz Post)', 'kyrgyzpost');
INSERT INTO `express` VALUES (882, '跨跃国际', 'kyue');
INSERT INTO `express` VALUES (883, '蓝镖快递', 'labiaokuaidi');
INSERT INTO `express` VALUES (884, '蓝弧快递', 'lahukuaidi');
INSERT INTO `express` VALUES (885, '老挝(Lao Express) ', 'lao');
INSERT INTO `express` VALUES (886, '塞内加尔', 'laposte');
INSERT INTO `express` VALUES (887, '林安物流', 'lasy56');
INSERT INTO `express` VALUES (888, '拉脱维亚(Latvijas Pasts)', 'latvia');
INSERT INTO `express` VALUES (889, '立白宝凯物流', 'lbbk');
INSERT INTO `express` VALUES (890, '林道国际快递-英文', 'ldxpres');
INSERT INTO `express` VALUES (891, '乐递供应链', 'ledii');
INSERT INTO `express` VALUES (892, '云豹国际货运', 'leopard');
INSERT INTO `express` VALUES (893, '莱索托(Lesotho Post)', 'lesotho');
INSERT INTO `express` VALUES (894, '美联快递', 'letseml');
INSERT INTO `express` VALUES (895, 'lazada', 'lgs');
INSERT INTO `express` VALUES (896, '联运快递', 'liayu');
INSERT INTO `express` VALUES (897, '黎巴嫩(Liba Post)', 'libapost');
INSERT INTO `express` VALUES (898, 'Liex', 'liex');
INSERT INTO `express` VALUES (899, '丽狮物流', 'lishi');
INSERT INTO `express` VALUES (900, '立陶宛（Lietuvos pa?tas）', 'lithuaia');
INSERT INTO `express` VALUES (901, '小熊物流', 'littlebearbear');
INSERT INTO `express` VALUES (902, '良藤国际速递', 'lmfex');
INSERT INTO `express` VALUES (903, '華信物流WTO', 'logistics');
INSERT INTO `express` VALUES (904, '长风物流', 'logvast');
INSERT INTO `express` VALUES (905, '恒通快递', 'lqht');
INSERT INTO `express` VALUES (906, '乐天速递', 'ltexp');
INSERT INTO `express` VALUES (907, '联通快递', 'ltparcel');
INSERT INTO `express` VALUES (908, '论道国际物流', 'ludao');
INSERT INTO `express` VALUES (909, '卢森堡(Luxembourg Post)', 'luxembourg');
INSERT INTO `express` VALUES (910, '马其顿(Macedoia Post)', 'macedoia');
INSERT INTO `express` VALUES (911, '麦力快递', 'mailikuaidi');
INSERT INTO `express` VALUES (912, '迈隆递运', 'mailogdy');
INSERT INTO `express` VALUES (913, '马尔代夫(Maldives Post)', 'maldives');
INSERT INTO `express` VALUES (914, '马耳他（Malta Post）', 'malta');
INSERT INTO `express` VALUES (915, '芒果速递', 'magguo');
INSERT INTO `express` VALUES (916, '今枫国际快运', 'mapleexpress');
INSERT INTO `express` VALUES (917, '毛里求斯(Mauritius Post)', 'mauritius');
INSERT INTO `express` VALUES (918, '美邦国际快递', 'meibag');
INSERT INTO `express` VALUES (919, '美达快递', 'meidaexpress');
INSERT INTO `express` VALUES (920, '美泰物流', 'meitai');
INSERT INTO `express` VALUES (921, '墨西哥（Correos de Mexico）', 'mexico');
INSERT INTO `express` VALUES (922, 'Mexico Seda Express', 'mexicodeda');
INSERT INTO `express` VALUES (923, '银河物流', 'milkyway');
INSERT INTO `express` VALUES (924, '美龙快递', 'mjexp');
INSERT INTO `express` VALUES (925, '摩尔多瓦(Posta Moldovei)', 'moldova');
INSERT INTO `express` VALUES (926, '蒙古国(Mogol Post) ', 'mogolpost');
INSERT INTO `express` VALUES (927, '黑山(Posta Cre Gore)', 'moteegro');
INSERT INTO `express` VALUES (928, '摩洛哥 ( Morocco Post )', 'morocco');
INSERT INTO `express` VALUES (929, 'MRW', 'mrw');
INSERT INTO `express` VALUES (930, 'Mexico Multipack', 'multipack');
INSERT INTO `express` VALUES (931, '中俄速通（淼信）', 'mxe56');
INSERT INTO `express` VALUES (932, '新亚物流', 'alexpress');
INSERT INTO `express` VALUES (933, '纳米比亚(NamPost)', 'amibia');
INSERT INTO `express` VALUES (934, '红马速递', 'edahm');
INSERT INTO `express` VALUES (935, '尼泊尔（Nepal Postal Services）', 'epalpost');
INSERT INTO `express` VALUES (936, 'Newgistics', 'ewgistics');
INSERT INTO `express` VALUES (937, '尼日利亚(Nigeria Postal)', 'igeriapost');
INSERT INTO `express` VALUES (938, '浩博物流', 'jhaobo');
INSERT INTO `express` VALUES (939, 'NLE', 'le');
INSERT INTO `express` VALUES (940, '亚欧专线', 'lebv');
INSERT INTO `express` VALUES (941, 'Nova Poshta', 'ovaposhta');
INSERT INTO `express` VALUES (942, '诺尔国际物流', 'uoer');
INSERT INTO `express` VALUES (943, '偌亚奥国际快递', 'uoyaao');
INSERT INTO `express` VALUES (944, 'OCA Argetia', 'ocaarge');
INSERT INTO `express` VALUES (945, '阿曼(Oma Post)', 'oma');
INSERT INTO `express` VALUES (946, '爱沙尼亚(Eesti Post)', 'omiva');
INSERT INTO `express` VALUES (947, '昂威物流', 'oway');
INSERT INTO `express` VALUES (948, 'OPEK', 'opek');
INSERT INTO `express` VALUES (949, '波音速递', 'overseaex');
INSERT INTO `express` VALUES (950, '巴基斯坦(Pakista Post)', 'pakista');
INSERT INTO `express` VALUES (951, '巴拉圭(Correo Paraguayo)', 'paraguay');
INSERT INTO `express` VALUES (952, '诚一物流', 'parcelchia');
INSERT INTO `express` VALUES (953, '全球速递', 'pdstow');
INSERT INTO `express` VALUES (954, '陪行物流', 'peixigwuliu');
INSERT INTO `express` VALUES (955, '鹏程快递', 'pegcheg');
INSERT INTO `express` VALUES (956, '品速心达快递', 'pisuxida');
INSERT INTO `express` VALUES (957, '品信快递', 'pixikuaidi');
INSERT INTO `express` VALUES (958, '先锋国际快递', 'pioeer');
INSERT INTO `express` VALUES (959, '北极星快运', 'polarisexpress');
INSERT INTO `express` VALUES (960, '葡萄牙（Portugal CTT）', 'portugalctt');
INSERT INTO `express` VALUES (961, 'Portugal Seur', 'portugalseur');
INSERT INTO `express` VALUES (962, '坦桑尼亚（Tazaia Posts Corporatio）', 'posta');
INSERT INTO `express` VALUES (963, 'PostElbe', 'postelbe');
INSERT INTO `express` VALUES (964, 'PostNord(Poste AB)', 'posteab');
INSERT INTO `express` VALUES (965, '挪威（Poste Norge）', 'posteorge');
INSERT INTO `express` VALUES (966, '巴布亚新几内亚(PNG Post)', 'postpg');
INSERT INTO `express` VALUES (967, 'Purolator', 'purolator');
INSERT INTO `express` VALUES (968, 'ANTS EXPRESS', 'qdats');
INSERT INTO `express` VALUES (969, '7E速递', 'qesd');
INSERT INTO `express` VALUES (970, '雪域快递', 'qhxykd');
INSERT INTO `express` VALUES (971, '千顺快递', 'qskdyxgs');
INSERT INTO `express` VALUES (972, 'Quatium', 'quatium');
INSERT INTO `express` VALUES (973, '全之鑫物流', 'qzx56');
INSERT INTO `express` VALUES (974, 'Red Express', 'redexpress');
INSERT INTO `express` VALUES (975, '叙利亚(Syria Post)', 'republic');
INSERT INTO `express` VALUES (976, '睿和泰速运', 'rhtexpress');
INSERT INTO `express` VALUES (977, '荣庆物流', 'roki');
INSERT INTO `express` VALUES (978, '罗马尼亚（Posta Romaia）', 'romaia');
INSERT INTO `express` VALUES (979, '日日通国际', 'rrthk');
INSERT INTO `express` VALUES (980, '卢旺达(Rwada i-posita)', 'rwada');
INSERT INTO `express` VALUES (981, '萨摩亚(Samoa Post)', 'samoa');
INSERT INTO `express` VALUES (982, '沙特阿拉伯(Saudi Post)', 'saudipost');
INSERT INTO `express` VALUES (983, '中加国际快递', 'scic');
INSERT INTO `express` VALUES (984, '四川星程快递', 'scxigcheg');
INSERT INTO `express` VALUES (985, '速呈', 'sczpds');
INSERT INTO `express` VALUES (986, 'Selektvracht', 'selektvracht');
INSERT INTO `express` VALUES (987, '塞尔维亚(PE Post of Serbia)', 'serbia');
INSERT INTO `express` VALUES (988, 'Iteratioal Seur', 'seur');
INSERT INTO `express` VALUES (989, '澳丰速递', 'sfau');
INSERT INTO `express` VALUES (990, '曹操到', 'sfpost');
INSERT INTO `express` VALUES (991, '衫达快运', 'shada56');
INSERT INTO `express` VALUES (992, '上海无疆for买卖宝', 'shaghaiwujiagmmb');
INSERT INTO `express` VALUES (993, '尚途国际货运', 'shagtuguoji');
INSERT INTO `express` VALUES (994, '捎客物流', 'shaoke');
INSERT INTO `express` VALUES (995, '商海德物流', 'shd56');
INSERT INTO `express` VALUES (996, '神骏物流', 'sheju');
INSERT INTO `express` VALUES (997, '神马快递', 'shema');
INSERT INTO `express` VALUES (998, '阳光快递', 'shiigexpress');
INSERT INTO `express` VALUES (999, '王牌快递', 'shipbyace');
INSERT INTO `express` VALUES (1000, '苏豪快递', 'shipsoho');
INSERT INTO `express` VALUES (1001, '世运快递', 'shiyukuaidi');
INSERT INTO `express` VALUES (1002, '顺丰同城', 'shufegtogcheg');
INSERT INTO `express` VALUES (1003, '顺士达速运', 'shushid');
INSERT INTO `express` VALUES (1004, '四海快递', 'sihaiet');
INSERT INTO `express` VALUES (1005, '四海捷运', 'sihiexpress');
INSERT INTO `express` VALUES (1006, '中外运速递-中文', 'sioex');
INSERT INTO `express` VALUES (1007, 'Siodemka', 'siodemka');
INSERT INTO `express` VALUES (1008, '易普递', 'sixroad');
INSERT INTO `express` VALUES (1009, 'SkyNet Malaysia', 'skyetmalaysia');
INSERT INTO `express` VALUES (1010, 'skyetworldwide', 'skyetworldwide');
INSERT INTO `express` VALUES (1011, '荷兰Sky Post', 'skypost');
INSERT INTO `express` VALUES (1012, '斯洛伐克(Sloveská Posta)', 'slovak');
INSERT INTO `express` VALUES (1013, '斯里兰卡(Sri Laka Post)', 'slpost');
INSERT INTO `express` VALUES (1014, '嗖一下同城快递', 'sofast56');
INSERT INTO `express` VALUES (1015, '南非（South Africa Post Office）', 'southafrica');
INSERT INTO `express` VALUES (1016, '行必达', 'speeda');
INSERT INTO `express` VALUES (1017, '申必达', 'speedoex');
INSERT INTO `express` VALUES (1018, '首通快运', 'staky');
INSERT INTO `express` VALUES (1019, '星速递', 'starex');
INSERT INTO `express` VALUES (1020, '星运快递', 'staryvr');
INSERT INTO `express` VALUES (1021, '速豹', 'subaoex');
INSERT INTO `express` VALUES (1022, '速呈宅配', 'sucheg');
INSERT INTO `express` VALUES (1023, '苏丹（Sudapost）', 'sudapost');
INSERT INTO `express` VALUES (1024, '速风快递', 'sufegkuaidi');
INSERT INTO `express` VALUES (1025, '郑州速捷', 'sujievip');
INSERT INTO `express` VALUES (1026, '速配欧翼', 'superoz');
INSERT INTO `express` VALUES (1027, '速品快递', 'supiexpress');
INSERT INTO `express` VALUES (1028, '瑞士邮政', 'swisspostc');
INSERT INTO `express` VALUES (1029, '深圳DPEX', 'szdpex');
INSERT INTO `express` VALUES (1030, '天美快递', 'taimek');
INSERT INTO `express` VALUES (1031, '坦桑尼亚(Tazaia Posts)', 'tazaia');
INSERT INTO `express` VALUES (1032, 'TCI XPS', 'tcixps');
INSERT INTO `express` VALUES (1033, 'TD Cargo', 'tdcargo');
INSERT INTO `express` VALUES (1034, '加拿大雷霆快递', 'thuderexpress');
INSERT INTO `express` VALUES (1035, '天翔快递', 'tiaxiag');
INSERT INTO `express` VALUES (1036, '万家通快递', 'timedg');
INSERT INTO `express` VALUES (1037, '天联快运', 'tlky');
INSERT INTO `express` VALUES (1038, '株式会社T.M.G', 'tmg');
INSERT INTO `express` VALUES (1039, 'TNT Italy', 'ttitaly');
INSERT INTO `express` VALUES (1040, 'TNT Post', 'ttpostc');
INSERT INTO `express` VALUES (1041, 'TNY物流', 'ty');
INSERT INTO `express` VALUES (1042, '通达兴物流', 'togdaxig');
INSERT INTO `express` VALUES (1043, '顶世国际物流', 'topshey');
INSERT INTO `express` VALUES (1044, '天天欧洲物流', 'ttkeurope');
INSERT INTO `express` VALUES (1045, '突尼斯EMS(Rapid-Poste)', 'tuisia');
INSERT INTO `express` VALUES (1046, '海龟国际快递', 'turtle');
INSERT INTO `express` VALUES (1047, 'UEX国际物流', 'uex');
INSERT INTO `express` VALUES (1048, '欧洲UEX', 'uexiex');
INSERT INTO `express` VALUES (1049, '乌克兰小包、大包(UkrPoshta)', 'ukraie');
INSERT INTO `express` VALUES (1050, '优联吉运', 'uluckex');
INSERT INTO `express` VALUES (1051, 'UPS Mail Iovatios', 'upsmailio');
INSERT INTO `express` VALUES (1052, '华夏国际速递', 'uschuaxia');
INSERT INTO `express` VALUES (1053, 'UTAO优到', 'utaoscm');
INSERT INTO `express` VALUES (1054, '乌兹别克斯坦(Post of Uzbekista)', 'uzbekista');
INSERT INTO `express` VALUES (1055, '瓦努阿图(Vauatu Post)', 'vauatu');
INSERT INTO `express` VALUES (1056, '越南小包(Vietam Posts)', 'vietam');
INSERT INTO `express` VALUES (1057, '鹰运国际速递', 'vipexpress');
INSERT INTO `express` VALUES (1058, '万博快递', 'waboex');
INSERT INTO `express` VALUES (1059, '宁夏万家通', 'wajiatog');
INSERT INTO `express` VALUES (1060, '万达美', 'wdm');
INSERT INTO `express` VALUES (1061, '威速递', 'wexpress');
INSERT INTO `express` VALUES (1062, '香港伟豪国际物流', 'whgjkd');
INSERT INTO `express` VALUES (1063, '万邑通', 'wiit');
INSERT INTO `express` VALUES (1064, '凡仕特物流', 'wlfast');
INSERT INTO `express` VALUES (1065, '沃埃家', 'wowvip');
INSERT INTO `express` VALUES (1066, 'WTD海外通', 'wtdex');
INSERT INTO `express` VALUES (1067, '伍圆速递', 'wuyuasudi');
INSERT INTO `express` VALUES (1068, '万运国际快递', 'wygj168');
INSERT INTO `express` VALUES (1069, '微转运', 'wzhauyu');
INSERT INTO `express` VALUES (1070, '国晶物流', 'xdshippig');
INSERT INTO `express` VALUES (1071, '西安城联速递', 'xiachegliasudi');
INSERT INTO `express` VALUES (1072, '小C海淘', 'xiaocex');
INSERT INTO `express` VALUES (1073, '西安喜来快递', 'xilaikd');
INSERT INTO `express` VALUES (1074, '西邮寄', 'xipost');
INSERT INTO `express` VALUES (1075, '鑫通宝物流', 'xtb');
INSERT INTO `express` VALUES (1076, '鑫远东速运', 'xyd666');
INSERT INTO `express` VALUES (1077, 'YCG物流', 'ycgglobal');
INSERT INTO `express` VALUES (1078, '也门(Yeme Post)', 'yeme');
INSERT INTO `express` VALUES (1079, '宇航通物流', 'yhtlogistics');
INSERT INTO `express` VALUES (1080, '一邦速递', 'yibagwuliu');
INSERT INTO `express` VALUES (1081, '驿递汇速递', 'yidihui');
INSERT INTO `express` VALUES (1082, '易航物流', 'yihagmall');
INSERT INTO `express` VALUES (1083, '一柒国际物流', 'yiqiguojiwuliu');
INSERT INTO `express` VALUES (1084, '亿顺航', 'yishuhag');
INSERT INTO `express` VALUES (1085, '易通达', 'yitogda');
INSERT INTO `express` VALUES (1086, '易邮速运', 'yiyou');
INSERT INTO `express` VALUES (1087, '武汉优进汇', 'yjhgo');
INSERT INTO `express` VALUES (1088, '洋口岸', 'ykoua');
INSERT INTO `express` VALUES (1089, '永邦国际物流', 'yogbagwuliu');
INSERT INTO `express` VALUES (1090, '友家速递', 'youjia');
INSERT INTO `express` VALUES (1091, '壹品速递', 'ypsd');
INSERT INTO `express` VALUES (1092, '运通快运', 'ytky168');
INSERT INTO `express` VALUES (1093, '远盾物流', 'yuadu');
INSERT INTO `express` VALUES (1094, '远航国际快运', 'yuahhk');
INSERT INTO `express` VALUES (1095, '粤中国际货运代理（上海）有限公司', 'yuezhogsh');
INSERT INTO `express` VALUES (1096, '御风速运', 'yufeg');
INSERT INTO `express` VALUES (1097, '德国云快递', 'yuexpress');
INSERT INTO `express` VALUES (1098, '远为快递', 'ywexpress');
INSERT INTO `express` VALUES (1099, '西安运逸快递', 'yyexp');
INSERT INTO `express` VALUES (1100, '志腾物流', 'zhitegwuliu');

